import React, { useMemo, useState } from 'react';
import { VaultSecret } from '@hermes-hub/types';
import { Copy, Eye, EyeOff, KeyRound, LockKeyhole, Plus, Search, ShieldCheck, Trash2, X } from 'lucide-react';

interface VaultViewProps {
  secrets: VaultSecret[];
  onSaveSecret: (secret: VaultSecret) => void | Promise<void>;
  onRevealSecret: (id: string) => Promise<VaultSecret | null>;
  onDeleteSecret: (id: string) => Promise<boolean>;
}

export const VaultView: React.FC<VaultViewProps> = ({ secrets, onSaveSecret, onRevealSecret, onDeleteSecret }) => {
  const [query, setQuery] = useState('');
  const [visible, setVisible] = useState<Set<string>>(new Set());
  const [revealedValues, setRevealedValues] = useState<Record<string, string>>({});
  const [isAdding, setIsAdding] = useState(false);
  const [draft, setDraft] = useState({ key: '', value: '', category: 'API Keys' as VaultSecret['category'], description: '' });
  const filtered = useMemo(() => secrets.filter((secret) => `${secret.key} ${secret.category} ${secret.description || ''}`.toLowerCase().includes(query.toLowerCase())), [secrets, query]);
  const toggle = async (id: string) => {
    if (visible.has(id)) { setVisible((current) => { const next = new Set(current); next.delete(id); return next; }); return; }
    const revealed = await onRevealSecret(id);
    if (!revealed) return;
    setRevealedValues((current) => ({ ...current, [id]: revealed.value }));
    setVisible((current) => new Set(current).add(id));
  };
  const save = async () => { if (!draft.key.trim() || !draft.value.trim()) return; await onSaveSecret({ id: `sec-${Date.now()}`, key: draft.key.trim().toUpperCase(), value: draft.value, category: draft.category, description: draft.description.trim(), isMasked: true, updatedAt: new Date().toISOString(), originDevice: 'This device' }); setDraft({ key: '', value: '', category: 'API Keys', description: '' }); setIsAdding(false); };
  const remove = async (secret: VaultSecret) => { if (!window.confirm(`Delete ${secret.key} from the encrypted vault?`)) return; await onDeleteSecret(secret.id); };
  return <div className="mx-auto max-w-6xl space-y-6 pb-12">
    <section className="relative overflow-hidden rounded-2xl border border-primary/20 bg-gradient-to-br from-primary/10 via-card to-card p-6">
      <div className="absolute -right-10 -top-10 h-40 w-40 rounded-full bg-primary/10 blur-3xl" />
      <div className="relative flex flex-col gap-4 sm:flex-row sm:items-center sm:justify-between"><div className="flex gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-xl border border-primary/20 bg-primary/10 text-primary"><LockKeyhole className="h-6 w-6" /></span><div><h2 className="text-xl font-bold">Encrypted secrets vault</h2><p className="mt-1 max-w-2xl text-sm text-muted-foreground">Credentials stay encrypted on your devices and are never written to logs or sync manifests.</p></div></div><button onClick={() => setIsAdding(true)} className="flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground"><Plus className="h-4 w-4" />Add secret</button></div>
    </section>
    <div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-semibold">Stored credentials</h3><p className="text-xs text-muted-foreground">{secrets.length} secrets protected by the OS credential store</p></div><label className="flex w-full items-center gap-2 rounded-xl border border-border bg-card px-3 sm:w-72"><Search className="h-4 w-4 text-muted-foreground" /><input value={query} onChange={(e) => setQuery(e.target.value)} placeholder="Search secrets" className="h-10 w-full bg-transparent text-sm outline-none" /></label></div>
    <div className="grid gap-3 md:grid-cols-2">{filtered.map((secret) => <article key={secret.id} className="rounded-2xl border border-border bg-card p-4 shadow-sm transition-colors hover:border-primary/30"><div className="flex items-start gap-3"><span className="rounded-xl bg-primary/10 p-2.5 text-primary"><KeyRound className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex items-center gap-2"><h4 className="truncate font-mono text-sm font-semibold">{secret.key}</h4><span className="rounded-full bg-muted px-2 py-0.5 text-[10px] text-muted-foreground">{secret.category}</span></div><p className="mt-1 truncate text-xs text-muted-foreground">{secret.description || 'No description'}</p></div><ShieldCheck className="h-4 w-4 text-emerald-500" /></div><div className="mt-4 flex items-center gap-2 rounded-xl border border-border/70 bg-background/60 px-3 py-2"><code className="min-w-0 flex-1 truncate text-xs text-muted-foreground">{visible.has(secret.id) ? revealedValues[secret.id] || secret.value : '••••••••••••••••••••••••'}</code><button aria-label={visible.has(secret.id) ? 'Hide secret' : 'Reveal secret'} onClick={() => toggle(secret.id)} className="rounded-md p-1.5 text-muted-foreground hover:bg-muted hover:text-foreground">{visible.has(secret.id) ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button><button aria-label="Copy secret" disabled={!revealedValues[secret.id]} onClick={() => navigator.clipboard?.writeText(revealedValues[secret.id])} className="rounded-md p-1.5 text-muted-foreground hover:bg-muted hover:text-foreground disabled:opacity-30"><Copy className="h-4 w-4" /></button><button aria-label="Delete secret" onClick={() => remove(secret)} className="rounded-md p-1.5 text-muted-foreground hover:bg-rose-500/10 hover:text-rose-500"><Trash2 className="h-4 w-4" /></button></div></article>)}</div>
    {!filtered.length && <div className="rounded-2xl border border-dashed border-border py-16 text-center text-sm text-muted-foreground">No secrets match “{query}”.</div>}
    {isAdding && <div className="fixed inset-0 z-[80] flex items-center justify-center bg-background/75 p-4 backdrop-blur-sm"><div className="w-full max-w-md rounded-2xl border border-border bg-popover p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-bold">Add encrypted secret</h3><p className="text-xs text-muted-foreground">Stored securely on this device.</p></div><button onClick={() => setIsAdding(false)} className="rounded-lg p-2 text-muted-foreground hover:bg-muted"><X className="h-4 w-4" /></button></div><div className="space-y-3"><input value={draft.key} onChange={(e) => setDraft({ ...draft, key: e.target.value })} placeholder="SECRET_NAME" className="h-11 w-full rounded-xl border border-input bg-background px-3 font-mono text-sm outline-none focus:ring-2 focus:ring-ring" /><select value={draft.category} onChange={(e) => setDraft({ ...draft, category: e.target.value as VaultSecret['category'] })} className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none">{['API Keys', 'Auth Tokens', 'Tailscale', 'Custom'].map((category) => <option key={category}>{category}</option>)}</select><input type="password" value={draft.value} onChange={(e) => setDraft({ ...draft, value: e.target.value })} placeholder="Secret value" className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm outline-none focus:ring-2 focus:ring-ring" /><textarea value={draft.description} onChange={(e) => setDraft({ ...draft, description: e.target.value })} placeholder="Description (optional)" className="min-h-20 w-full resize-none rounded-xl border border-input bg-background p-3 text-sm outline-none" /></div><div className="mt-5 flex justify-end gap-2"><button onClick={() => setIsAdding(false)} className="rounded-xl border border-border px-4 py-2 text-sm font-medium">Cancel</button><button disabled={!draft.key.trim() || !draft.value.trim()} onClick={save} className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-40">Encrypt & save</button></div></div></div>}
  </div>;
};
