import React, { useEffect, useMemo, useState } from 'react';
import { SharedVaultStatus, VaultEnvironmentProfile, VaultSecret } from '@hermes-hub/types';
import { CheckCircle2, Clipboard, Copy, Eye, EyeOff, FileKey2, KeyRound, Lock, LockKeyhole, Plus, Search, ServerCog, ShieldCheck, Trash2, X } from 'lucide-react';

interface VaultViewProps {
  secrets: VaultSecret[];
  status: SharedVaultStatus | null;
  demoMode: boolean;
  onRefresh: () => Promise<void>;
  onSaveSecret: (secret: VaultSecret) => void | Promise<void>;
  onRevealSecret: (id: string) => Promise<VaultSecret | null>;
  onDeleteSecret: (id: string) => Promise<boolean>;
}

const categories: VaultSecret['category'][] = ['API Keys', 'Auth Tokens', 'Passwords', 'SSH Keys', 'Certificates', 'Recovery Codes', 'Tailscale', 'Custom'];

function parseEnv(text: string) {
  return text.split(/\r?\n/).map((line) => line.trim()).filter((line) => line && !line.startsWith('#')).map((line) => {
    const normalized = line.startsWith('export ') ? line.slice(7) : line;
    const separator = normalized.indexOf('=');
    if (separator < 1) return null;
    const key = normalized.slice(0, separator).trim();
    let value = normalized.slice(separator + 1).trim();
    if ((value.startsWith('"') && value.endsWith('"')) || (value.startsWith("'") && value.endsWith("'"))) value = value.slice(1, -1);
    return /^[A-Za-z_][A-Za-z0-9_]*$/.test(key) ? { key, value, isMasked: false as const } : null;
  }).filter((item): item is { key: string; value: string; isMasked: false } => Boolean(item));
}

function serializeEnv(profile: VaultEnvironmentProfile): string {
  return profile.variables.map((variable) => `${variable.key}=${JSON.stringify(variable.value)}`).join('\n');
}

export const VaultView: React.FC<VaultViewProps> = ({ secrets, status, demoMode, onRefresh, onSaveSecret, onRevealSecret, onDeleteSecret }) => {
  const [tab, setTab] = useState<'secrets' | 'environments' | 'access'>('secrets');
  const [query, setQuery] = useState('');
  const [visible, setVisible] = useState<Set<string>>(new Set());
  const [revealedValues, setRevealedValues] = useState<Record<string, string>>({});
  const [isAdding, setIsAdding] = useState(false);
  const [draft, setDraft] = useState({ key: '', value: '', category: 'API Keys' as VaultSecret['category'], description: '', tags: '', expiresAt: '' });
  const [password, setPassword] = useState('');
  const [confirmPassword, setConfirmPassword] = useState('');
  const [remember, setRemember] = useState(true);
  const [importExisting, setImportExisting] = useState(true);
  const [busy, setBusy] = useState(false);
  const [notice, setNotice] = useState<string | null>(null);
  const [environments, setEnvironments] = useState<VaultEnvironmentProfile[]>([]);
  const [envEditor, setEnvEditor] = useState<{ id?: string; name: string; description: string; text: string } | null>(null);
  const filtered = useMemo(() => secrets.filter((secret) => `${secret.key} ${secret.category} ${secret.description || ''} ${(secret.tags || []).join(' ')}`.toLowerCase().includes(query.toLowerCase())), [secrets, query]);

  const loadEnvironments = async () => {
    if (demoMode || status?.locked || !window.hermesHub) return;
    try { setEnvironments(await window.hermesHub.getVaultEnvironments()); } catch (error) { setNotice(error instanceof Error ? error.message : 'Could not load environments.'); }
  };
  useEffect(() => { void loadEnvironments(); }, [status?.locked, status?.revision]);

  const configureOrUnlock = async () => {
    if (!window.hermesHub || password.length < 8) return;
    if (!status?.configured && password !== confirmPassword) { setNotice('The two passwords do not match.'); return; }
    setBusy(true); setNotice(null);
    try {
      if (status?.configured) await window.hermesHub.unlockSharedVault({ password, rememberOnThisPc: remember });
      else await window.hermesHub.setupSharedVault({ password, rememberOnThisPc: remember, importExistingLocalVault: importExisting });
      setPassword(''); setConfirmPassword(''); await onRefresh();
      setNotice(status?.configured ? 'Shared Vault unlocked.' : 'Shared Vault created. Use this same password on every PC.');
    } catch (error) { setNotice(error instanceof Error ? error.message : 'Vault operation failed.'); }
    finally { setBusy(false); }
  };

  const toggle = async (id: string) => {
    if (visible.has(id)) { setVisible((current) => { const next = new Set(current); next.delete(id); return next; }); return; }
    const revealed = await onRevealSecret(id); if (!revealed) return;
    setRevealedValues((current) => ({ ...current, [id]: revealed.value }));
    setVisible((current) => new Set(current).add(id));
    window.setTimeout(() => setVisible((current) => { const next = new Set(current); next.delete(id); return next; }), 60_000);
  };

  const copyValue = async (value: string) => {
    await navigator.clipboard.writeText(value);
    setNotice('Copied. The clipboard will be cleared after 30 seconds if it still contains this value.');
    window.setTimeout(async () => { try { if (await navigator.clipboard.readText() === value) await navigator.clipboard.writeText(''); } catch {} }, 30_000);
  };

  const save = async () => {
    if (!draft.key.trim() || !draft.value) return;
    await onSaveSecret({ id: `sec-${Date.now()}`, key: draft.key.trim(), value: draft.value, category: draft.category, description: draft.description.trim(), tags: draft.tags.split(',').map((tag) => tag.trim()).filter(Boolean), expiresAt: draft.expiresAt || undefined, isMasked: true, updatedAt: new Date().toISOString(), originDevice: 'This device' });
    setDraft({ key: '', value: '', category: 'API Keys', description: '', tags: '', expiresAt: '' }); setIsAdding(false); await onRefresh();
  };
  const remove = async (secret: VaultSecret) => { if (!window.confirm(`Delete ${secret.key} from the shared vault?`)) return; await onDeleteSecret(secret.id); await onRefresh(); };
  const openEnvironment = async (profile: VaultEnvironmentProfile) => { if (demoMode) { setEnvEditor({ id: profile.id, name: profile.name, description: profile.description || '', text: '# Demo Mode environment values are not persisted' }); return; } const revealed = await window.hermesHub?.getVaultEnvironment(profile.id); if (revealed) setEnvEditor({ id: revealed.id, name: revealed.name, description: revealed.description || '', text: serializeEnv(revealed) }); };
  const saveEnvironment = async () => {
    if (!window.hermesHub || !envEditor?.name.trim()) return;
    const variables = parseEnv(envEditor.text); if (!variables.length) { setNotice('Add at least one valid NAME=value line.'); return; }
    if (demoMode) { const profile = { id: envEditor.id || `env-${Date.now()}`, name: envEditor.name.trim(), description: envEditor.description.trim(), variables: variables.map((variable) => ({ ...variable, value: '', isMasked: true })), updatedAt: new Date().toISOString(), originDevice: 'Demo PC' }; setEnvironments((current) => [profile, ...current.filter((item) => item.id !== profile.id)]); setEnvEditor(null); setNotice('Demo environment saved for this session only.'); return; }
    await window.hermesHub.saveVaultEnvironment({ id: envEditor.id || `env-${Date.now()}`, name: envEditor.name.trim(), description: envEditor.description.trim(), variables, updatedAt: new Date().toISOString(), originDevice: 'This device' });
    setEnvEditor(null); await loadEnvironments(); await onRefresh(); setNotice(`Environment saved with ${variables.length} variable(s).`);
  };

  if (!status || (!demoMode && (!status.configured || status.locked))) return <div className="mx-auto max-w-xl space-y-5 py-10"><div className="rounded-3xl border border-primary/25 bg-gradient-to-br from-primary/10 via-card to-card p-7 shadow-xl"><div className="flex items-center gap-3"><span className="rounded-2xl bg-primary/10 p-3 text-primary"><LockKeyhole className="h-7 w-7" /></span><div><h2 className="text-xl font-bold">{status?.configured ? 'Unlock Shared Vault' : 'Create Shared Vault'}</h2><p className="mt-1 text-sm text-muted-foreground">{status?.configured ? 'Enter the same password used on your other PC.' : 'One password protects secrets and environments synchronized through your HermesHubData folder.'}</p></div></div><div className="mt-6 space-y-3"><input autoFocus type="password" value={password} onChange={(event) => setPassword(event.target.value)} onKeyDown={(event) => { if (event.key === 'Enter') void configureOrUnlock(); }} placeholder="Shared Vault password (8+ characters)" className="h-12 w-full rounded-xl border border-input bg-background px-4 outline-none focus:ring-2 focus:ring-ring" />{!status?.configured && <input type="password" value={confirmPassword} onChange={(event) => setConfirmPassword(event.target.value)} placeholder="Confirm password" className="h-12 w-full rounded-xl border border-input bg-background px-4 outline-none focus:ring-2 focus:ring-ring" />}<label className="flex items-start gap-2 text-xs text-muted-foreground"><input type="checkbox" checked={remember} onChange={(event) => setRemember(event.target.checked)} className="mt-0.5 accent-primary" /><span>Remember on this PC using Windows secure storage.</span></label>{!status?.configured && <label className="flex items-start gap-2 text-xs text-muted-foreground"><input type="checkbox" checked={importExisting} onChange={(event) => setImportExisting(event.target.checked)} className="mt-0.5 accent-primary" /><span>Import credentials from the previous local Vault, if present.</span></label>}</div><button disabled={busy || password.length < 8 || (!status?.configured && password !== confirmPassword)} onClick={() => void configureOrUnlock()} className="mt-5 w-full rounded-xl bg-primary px-4 py-3 text-sm font-semibold text-primary-foreground disabled:opacity-40">{busy ? 'Working…' : status?.configured ? 'Unlock Vault' : 'Create Shared Vault'}</button>{notice && <p className="mt-4 rounded-xl border border-amber-500/20 bg-amber-500/10 p-3 text-xs text-amber-600 dark:text-amber-300">{notice}</p>}</div></div>;

  return <div className="mx-auto max-w-6xl space-y-6 pb-12">
    <section className="rounded-2xl border border-primary/20 bg-gradient-to-br from-primary/10 via-card to-card p-6"><div className="flex flex-col gap-4 lg:flex-row lg:items-center lg:justify-between"><div className="flex gap-4"><span className="flex h-12 w-12 items-center justify-center rounded-xl border border-primary/20 bg-primary/10 text-primary"><LockKeyhole className="h-6 w-6" /></span><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-bold">Shared Vault</h2><span className="rounded-full bg-emerald-500/10 px-2 py-0.5 text-[10px] font-bold uppercase text-emerald-500"><CheckCircle2 className="mr-1 inline h-3 w-3" />{demoMode ? 'Demo' : 'Unlocked'}</span></div><p className="mt-1 max-w-2xl text-sm text-muted-foreground">One encrypted Vault for credentials and environments across your synchronized PCs.</p><p className="mt-2 break-all font-mono text-[10px] text-muted-foreground">Revision {status.revision} · {status.syncPath}</p></div></div>{!demoMode && <div className="flex gap-2"><button onClick={() => window.hermesHub?.openFolder(status.syncPath)} className="rounded-xl border border-border px-3 py-2 text-xs font-semibold hover:bg-muted">Open location</button><button onClick={async () => { await window.hermesHub?.lockSharedVault(); setVisible(new Set()); setRevealedValues({}); await onRefresh(); }} className="flex items-center gap-2 rounded-xl border border-border px-3 py-2 text-xs font-semibold hover:bg-muted"><Lock className="h-4 w-4" />Lock</button></div>}</div></section>
    {status.conflictFiles.length > 0 && <div className="rounded-xl border border-rose-500/25 bg-rose-500/10 p-4 text-xs text-rose-600 dark:text-rose-300">Syncthing created {status.conflictFiles.length} Vault conflict file(s). Preserve both copies until you compare them.</div>}
    {notice && <div className="flex items-center justify-between rounded-xl border border-primary/20 bg-primary/10 p-3 text-xs text-primary"><span>{notice}</span><button onClick={() => setNotice(null)} className="font-bold">Dismiss</button></div>}
    <div className="flex flex-wrap gap-2 border-b border-border pb-2">{([['secrets', KeyRound, `Secrets (${secrets.length})`], ['environments', ServerCog, `Environments (${environments.length})`], ['access', ShieldCheck, 'Access & password']] as const).map(([id, Icon, label]) => <button key={id} onClick={() => setTab(id)} className={`flex items-center gap-2 rounded-xl px-4 py-2 text-xs font-semibold ${tab === id ? 'bg-primary text-primary-foreground' : 'text-muted-foreground hover:bg-muted'}`}><Icon className="h-4 w-4" />{label}</button>)}</div>

    {tab === 'secrets' && <><div className="flex flex-col gap-3 sm:flex-row sm:items-center sm:justify-between"><label className="flex w-full items-center gap-2 rounded-xl border border-border bg-card px-3 sm:w-80"><Search className="h-4 w-4 text-muted-foreground" /><input value={query} onChange={(event) => setQuery(event.target.value)} placeholder="Search names, categories or tags" className="h-10 w-full bg-transparent text-sm outline-none" /></label><button onClick={() => setIsAdding(true)} className="flex items-center justify-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground"><Plus className="h-4 w-4" />Add secret</button></div><div className="grid gap-3 md:grid-cols-2">{filtered.map((secret) => <article key={secret.id} className="rounded-2xl border border-border bg-card p-4 shadow-sm"><div className="flex items-start gap-3"><span className="rounded-xl bg-primary/10 p-2.5 text-primary"><KeyRound className="h-5 w-5" /></span><div className="min-w-0 flex-1"><div className="flex flex-wrap items-center gap-2"><h4 className="truncate font-mono text-sm font-semibold">{secret.key}</h4><span className="rounded-full bg-muted px-2 py-0.5 text-[10px] text-muted-foreground">{secret.category}</span></div><p className="mt-1 truncate text-xs text-muted-foreground">{secret.description || 'No description'}</p>{secret.expiresAt && <p className="mt-1 text-[10px] text-amber-500">Expires {new Date(secret.expiresAt).toLocaleDateString()}</p>}</div><ShieldCheck className="h-4 w-4 text-emerald-500" /></div><div className="mt-4 flex items-center gap-2 rounded-xl border border-border/70 bg-background/60 px-3 py-2"><code className="min-w-0 flex-1 truncate text-xs text-muted-foreground">{visible.has(secret.id) ? revealedValues[secret.id] || secret.value : '••••••••••••••••••••••••'}</code><button aria-label={visible.has(secret.id) ? 'Hide secret' : 'Reveal secret'} onClick={() => void toggle(secret.id)} className="rounded-md p-1.5 text-muted-foreground hover:bg-muted">{visible.has(secret.id) ? <EyeOff className="h-4 w-4" /> : <Eye className="h-4 w-4" />}</button><button aria-label="Copy secret" onClick={async () => { const value = revealedValues[secret.id] || (await onRevealSecret(secret.id))?.value; if (value) await copyValue(value); }} className="rounded-md p-1.5 text-muted-foreground hover:bg-muted"><Copy className="h-4 w-4" /></button><button aria-label="Delete secret" onClick={() => void remove(secret)} className="rounded-md p-1.5 text-muted-foreground hover:bg-rose-500/10 hover:text-rose-500"><Trash2 className="h-4 w-4" /></button></div></article>)}</div>{!filtered.length && <div className="rounded-2xl border border-dashed border-border py-16 text-center text-sm text-muted-foreground">No matching secrets.</div>}</>}

    {tab === 'environments' && <div className="space-y-4"><div className="flex flex-col gap-3 rounded-2xl border border-border bg-card p-5 sm:flex-row sm:items-center sm:justify-between"><div><h3 className="font-semibold">Environment profiles</h3><p className="mt-1 text-xs text-muted-foreground">Paste a `.env` file once, then copy the complete profile on any synchronized PC.</p></div><button onClick={() => setEnvEditor({ name: '', description: '', text: '' })} className="flex items-center gap-2 rounded-xl bg-primary px-4 py-2.5 text-sm font-semibold text-primary-foreground"><Plus className="h-4 w-4" />New environment</button></div><div className="grid gap-3 md:grid-cols-2">{environments.map((profile) => <article key={profile.id} className="rounded-2xl border border-border bg-card p-4"><div className="flex items-start gap-3"><FileKey2 className="h-5 w-5 text-primary" /><div className="flex-1"><h4 className="font-semibold">{profile.name}</h4><p className="text-xs text-muted-foreground">{profile.description || 'Reusable environment variables'}</p><p className="mt-2 text-[10px] font-mono text-muted-foreground">{profile.variables.length} variables · {profile.originDevice}</p></div></div><div className="mt-4 flex gap-2"><button onClick={() => void openEnvironment(profile)} className="rounded-lg border border-border px-3 py-2 text-xs font-semibold hover:bg-muted">View / edit</button><button onClick={async () => { const full = await window.hermesHub?.getVaultEnvironment(profile.id); if (full) await copyValue(serializeEnv(full)); }} className="flex items-center gap-1 rounded-lg border border-border px-3 py-2 text-xs font-semibold hover:bg-muted"><Clipboard className="h-3.5 w-3.5" />Copy `.env`</button><button onClick={async () => { if (window.confirm(`Delete environment ${profile.name}?`)) { await window.hermesHub?.deleteVaultEnvironment(profile.id); await loadEnvironments(); await onRefresh(); } }} className="ml-auto rounded-lg p-2 text-muted-foreground hover:bg-rose-500/10 hover:text-rose-500"><Trash2 className="h-4 w-4" /></button></div></article>)}</div></div>}

    {tab === 'access' && (demoMode ? <div className="rounded-2xl border border-violet-500/20 bg-violet-500/10 p-5 text-sm text-violet-600 dark:text-violet-300">Password and access changes are disabled in Demo Mode.</div> : <div className="grid gap-4 lg:grid-cols-2"><section className="rounded-2xl border border-border bg-card p-5"><h3 className="font-semibold">Remembered access</h3><p className="mt-1 text-xs text-muted-foreground">{status.rememberedOnThisPc ? 'This Windows account unlocks the Vault automatically.' : 'The password is required after every restart.'}</p><button onClick={async () => { await window.hermesHub?.lockSharedVault(); await onRefresh(); }} className="mt-4 rounded-xl border border-border px-4 py-2 text-xs font-semibold hover:bg-muted">Forget password and lock</button></section><PasswordChange remember={status.rememberedOnThisPc} onChanged={async (message) => { setNotice(message); await onRefresh(); }} /></div>)}

    {isAdding && <SecretEditor draft={draft} setDraft={setDraft} onClose={() => setIsAdding(false)} onSave={() => void save()} />}
    {envEditor && <EnvironmentEditor editor={envEditor} setEditor={setEnvEditor} onClose={() => setEnvEditor(null)} onSave={() => void saveEnvironment()} />}
  </div>;
};

const SecretEditor: React.FC<{ draft: { key: string; value: string; category: VaultSecret['category']; description: string; tags: string; expiresAt: string }; setDraft: React.Dispatch<React.SetStateAction<{ key: string; value: string; category: VaultSecret['category']; description: string; tags: string; expiresAt: string }>>; onClose: () => void; onSave: () => void }> = ({ draft, setDraft, onClose, onSave }) => <div className="fixed inset-0 z-[80] flex items-center justify-center bg-background/75 p-4 backdrop-blur-sm"><div className="max-h-[90vh] w-full max-w-lg overflow-y-auto rounded-2xl border border-border bg-popover p-5 shadow-2xl"><div className="mb-5 flex items-center justify-between"><div><h3 className="font-bold">Add shared secret</h3><p className="text-xs text-muted-foreground">Available on PCs using the same Vault password.</p></div><button onClick={onClose} className="rounded-lg p-2 text-muted-foreground hover:bg-muted"><X className="h-4 w-4" /></button></div><div className="space-y-3"><input value={draft.key} onChange={(event) => setDraft({ ...draft, key: event.target.value })} placeholder="Name, for example GITHUB_TOKEN" className="h-11 w-full rounded-xl border border-input bg-background px-3 font-mono text-sm outline-none" /><select value={draft.category} onChange={(event) => setDraft({ ...draft, category: event.target.value as VaultSecret['category'] })} className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm">{categories.map((category) => <option key={category}>{category}</option>)}</select><textarea value={draft.value} onChange={(event) => setDraft({ ...draft, value: event.target.value })} placeholder="Secret, private key, certificate, or recovery codes" className="min-h-28 w-full resize-y rounded-xl border border-input bg-background p-3 font-mono text-xs outline-none" /><input value={draft.description} onChange={(event) => setDraft({ ...draft, description: event.target.value })} placeholder="Description (optional)" className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm" /><input value={draft.tags} onChange={(event) => setDraft({ ...draft, tags: event.target.value })} placeholder="Tags separated by commas" className="h-11 w-full rounded-xl border border-input bg-background px-3 text-sm" /><label className="block text-xs text-muted-foreground">Expiration (optional)<input type="date" value={draft.expiresAt} onChange={(event) => setDraft({ ...draft, expiresAt: event.target.value })} className="mt-1 h-11 w-full rounded-xl border border-input bg-background px-3 text-sm text-foreground" /></label></div><div className="mt-5 flex justify-end gap-2"><button onClick={onClose} className="rounded-xl border border-border px-4 py-2 text-sm">Cancel</button><button disabled={!draft.key.trim() || !draft.value} onClick={onSave} className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground disabled:opacity-40">Encrypt & save</button></div></div></div>;

const EnvironmentEditor: React.FC<{ editor: { id?: string; name: string; description: string; text: string }; setEditor: React.Dispatch<React.SetStateAction<{ id?: string; name: string; description: string; text: string } | null>>; onClose: () => void; onSave: () => void }> = ({ editor, setEditor, onClose, onSave }) => <div className="fixed inset-0 z-[80] flex items-center justify-center bg-background/75 p-4 backdrop-blur-sm"><div className="w-full max-w-2xl rounded-2xl border border-border bg-popover p-5 shadow-2xl"><div className="flex items-center justify-between"><div><h3 className="font-bold">Environment profile</h3><p className="text-xs text-muted-foreground">One `NAME=value` variable per line.</p></div><button onClick={onClose} className="rounded-lg p-2 text-muted-foreground hover:bg-muted"><X className="h-4 w-4" /></button></div><div className="mt-4 grid gap-3"><input value={editor.name} onChange={(event) => setEditor({ ...editor, name: event.target.value })} placeholder="Profile name" className="h-11 rounded-xl border border-input bg-background px-3 text-sm" /><input value={editor.description} onChange={(event) => setEditor({ ...editor, description: event.target.value })} placeholder="Description" className="h-11 rounded-xl border border-input bg-background px-3 text-sm" /><textarea spellCheck={false} value={editor.text} onChange={(event) => setEditor({ ...editor, text: event.target.value })} placeholder={'OPENAI_API_KEY=...\nGITHUB_TOKEN=...'} className="min-h-64 resize-y rounded-xl border border-input bg-background p-3 font-mono text-xs outline-none" /></div><div className="mt-4 flex items-center justify-between"><span className="text-xs text-muted-foreground">{parseEnv(editor.text).length} valid variables</span><div className="flex gap-2"><button onClick={onClose} className="rounded-xl border border-border px-4 py-2 text-sm">Cancel</button><button onClick={onSave} className="rounded-xl bg-primary px-4 py-2 text-sm font-semibold text-primary-foreground">Encrypt & save</button></div></div></div></div>;

const PasswordChange: React.FC<{ remember: boolean; onChanged: (message: string) => Promise<void> }> = ({ remember, onChanged }) => {
  const [current, setCurrent] = useState(''); const [next, setNext] = useState(''); const [confirm, setConfirm] = useState(''); const [busy, setBusy] = useState(false);
  const change = async () => { if (!window.hermesHub || next.length < 8 || next !== confirm) return; setBusy(true); try { await window.hermesHub.changeVaultPassword(current, next, remember); setCurrent(''); setNext(''); setConfirm(''); await onChanged('Shared Vault password changed. Enter the new password on other PCs.'); } catch (error) { await onChanged(error instanceof Error ? error.message : 'Password change failed.'); } finally { setBusy(false); } };
  return <section className="rounded-2xl border border-border bg-card p-5"><h3 className="font-semibold">Change shared password</h3><p className="mt-1 text-xs text-muted-foreground">Re-encrypts the Vault. Wait for Syncthing before opening it elsewhere.</p><div className="mt-4 space-y-2"><input type="password" value={current} onChange={(event) => setCurrent(event.target.value)} placeholder="Current password" className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm" /><input type="password" value={next} onChange={(event) => setNext(event.target.value)} placeholder="New password" className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm" /><input type="password" value={confirm} onChange={(event) => setConfirm(event.target.value)} placeholder="Confirm new password" className="h-10 w-full rounded-lg border border-input bg-background px-3 text-sm" /></div><button disabled={busy || next.length < 8 || next !== confirm || !current} onClick={() => void change()} className="mt-3 rounded-xl bg-primary px-4 py-2 text-xs font-semibold text-primary-foreground disabled:opacity-40">{busy ? 'Changing…' : 'Change password'}</button></section>;
};
