import {
  Device,
  HermesSession,
  HermesMemory,
  HermesSkill,
  HermesFile,
  VaultSecret,
  ActivityEvent,
  ActiveTransfer,
  BackupRecord,
  OverallStats,
} from '@hermes-hub/types';

export const MOCK_DEVICES: Device[] = [
  {
    deviceId: 'dev-desktop-001',
    deviceName: 'Studio PC',
    hostname: 'HERMES-STUDIO',
    os: 'windows',
    architecture: 'x64',
    appVersion: '0.1.0',
    agentVersion: '0.1.0',
    online: true,
    lastSeen: new Date().toISOString(),
    tailscale: {
      installed: true,
      connected: true,
      ip: '100.64.10.11',
      connectionType: 'direct',
      peersCount: 3,
    },
    syncthing: {
      installed: true,
      running: true,
      deviceId: 'SYNCTH-DEMO-STUDIO-8942-KM7D-9214',
      version: 'v1.27.12',
      foldersCount: 1,
    },
    hermes: {
      installed: true,
      running: true,
      version: '1.4.2',
      home: 'C:\\Users\\demo\\AppData\\Local\\hermes',
      profile: 'default',
    },
    data: {
      sessions: 243,
      memories: 52,
      skills: 18,
      totalSizeBytes: 391 * 1024 * 1024,
    },
    sync: {
      lastSync: new Date(Date.now() - 8 * 1000).toISOString(), // 8 seconds ago
      pendingFiles: 0,
      filesTransferred: 1420,
      bytesUploaded: 391 * 1024 * 1024,
      bytesDownloaded: 148 * 1024 * 1024,
      conflicts: 0,
      status: 'in-sync',
    },
    lastBackup: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    healthStatus: 'healthy',
  },
  {
    deviceId: 'dev-zenbook-002',
    deviceName: 'Travel Laptop',
    hostname: 'HERMES-TRAVEL',
    os: 'windows',
    architecture: 'x64',
    appVersion: '0.1.0',
    agentVersion: '0.1.0',
    online: true,
    lastSeen: new Date().toISOString(),
    tailscale: {
      installed: true,
      connected: true,
      ip: '100.64.10.12',
      connectionType: 'direct',
      peersCount: 3,
    },
    syncthing: {
      installed: true,
      running: true,
      deviceId: 'SYNCTH-DEMO-TRAVEL-3819-QL9A-1102',
      version: 'v1.27.12',
      foldersCount: 1,
    },
    hermes: {
      installed: true,
      running: true,
      version: '1.4.2',
      home: 'C:\\Users\\demo\\AppData\\Local\\hermes',
      profile: 'default',
    },
    data: {
      sessions: 243,
      memories: 52,
      skills: 18,
      totalSizeBytes: 391 * 1024 * 1024,
    },
    sync: {
      lastSync: new Date(Date.now() - 8 * 1000).toISOString(),
      pendingFiles: 0,
      filesTransferred: 890,
      bytesUploaded: 148 * 1024 * 1024,
      bytesDownloaded: 391 * 1024 * 1024,
      conflicts: 0,
      status: 'in-sync',
    },
    lastBackup: new Date(Date.now() - 50 * 60 * 1000).toISOString(),
    healthStatus: 'healthy',
  },
  {
    deviceId: 'dev-laptop-003',
    deviceName: 'Lab Laptop',
    hostname: 'HERMES-LAB-LINUX',
    os: 'linux',
    architecture: 'x64',
    appVersion: '0.0.9',
    agentVersion: '0.0.9',
    online: false,
    lastSeen: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(), // 2 days ago
    tailscale: {
      installed: true,
      connected: false,
      ip: '100.64.10.13',
      connectionType: 'derp-relay',
      peersCount: 0,
    },
    syncthing: {
      installed: true,
      running: false,
      deviceId: 'SYNCTH-OLD-LPTP-7712-ZX89-4401',
      version: 'v1.26.0',
      foldersCount: 1,
    },
    hermes: {
      installed: true,
      running: false,
      version: '1.3.8',
      home: '/home/demo/.hermes',
      profile: 'default',
    },
    data: {
      sessions: 101,
      memories: 38,
      skills: 12,
      totalSizeBytes: 180 * 1024 * 1024,
    },
    sync: {
      lastSync: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000).toISOString(),
      pendingFiles: 142, // 142 updates behind
      filesTransferred: 420,
      bytesUploaded: 45 * 1024 * 1024,
      bytesDownloaded: 120 * 1024 * 1024,
      conflicts: 0,
      status: 'offline',
    },
    lastBackup: new Date(Date.now() - 3 * 24 * 60 * 60 * 1000).toISOString(),
    healthStatus: 'offline',
  },
];

export const MOCK_OVERALL_STATS: OverallStats = {
  devicesCount: 3,
  onlineCount: 2,
  sessionsCount: 243,
  memoriesCount: 52,
  skillsCount: 18,
  pendingFilesCount: 0,
  conflictsCount: 0,
  syncHealth: 'all_synced',
};

export const MOCK_ACTIVE_TRANSFER: ActiveTransfer = {
  id: 'xfer-001',
  sourceDevice: 'Studio PC',
  targetDevice: 'Travel Laptop',
  progressPercentage: 89,
  bytesCurrent: 148 * 1024 * 1024,
  bytesTotal: 166 * 1024 * 1024,
  filesRemaining: 42,
  speedBytesPerSec: 11 * 1024 * 1024, // 11 MB/s
};

export const MOCK_SESSIONS: HermesSession[] = [
  {
    id: 'sess-001',
    title: 'Security lab review',
    createdAt: new Date(Date.now() - 2 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 21 * 60 * 1000).toISOString(),
    messagesCount: 97,
    model: 'claude-3-5-sonnet-20241022',
    tokensUsed: 42890,
    toolsUsed: ['terminal_exec', 'network_scanner', 'file_reader'],
    originDevice: 'dev-desktop-001',
    originDeviceName: 'Studio PC',
    revision: 14,
    syncStatus: 'synced',
    previewText: 'Analyzing attack vector and vulnerability scanning techniques for lab environment...',
  },
  {
    id: 'sess-002',
    title: 'Hermes Hub architecture',
    createdAt: new Date(Date.now() - 3 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 53 * 60 * 1000).toISOString(),
    messagesCount: 43,
    model: 'gpt-4o',
    tokensUsed: 19850,
    toolsUsed: ['code_writer', 'directory_analyzer'],
    originDevice: 'dev-zenbook-002',
    originDeviceName: 'Travel Laptop',
    revision: 8,
    syncStatus: 'synced',
    previewText: 'Local-first architecture design: Tailscale mesh, Syncthing transport, and Electron dashboard.',
  },
  {
    id: 'sess-003',
    title: 'Cryptography laboratory',
    createdAt: new Date(Date.now() - 26 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 24 * 60 * 60 * 1000).toISOString(),
    messagesCount: 84,
    model: 'deepseek-reasoner',
    tokensUsed: 62400,
    toolsUsed: ['python_repl', 'math_solver'],
    originDevice: 'dev-desktop-001',
    originDeviceName: 'Studio PC',
    revision: 21,
    syncStatus: 'synced',
    previewText: 'Elliptic curve Diffie-Hellman parameter generation and zero-knowledge proof verification...',
  },
  {
    id: 'sess-004',
    title: 'Monorepo refactor and testing',
    createdAt: new Date(Date.now() - 72 * 60 * 60 * 1000).toISOString(),
    updatedAt: new Date(Date.now() - 68 * 60 * 60 * 1000).toISOString(),
    messagesCount: 32,
    model: 'claude-3-5-sonnet-20241022',
    tokensUsed: 14200,
    toolsUsed: ['git_cli', 'test_runner'],
    originDevice: 'dev-zenbook-002',
    originDeviceName: 'Travel Laptop',
    revision: 5,
    syncStatus: 'synced',
    previewText: 'Pnpm workspaces setup with shared packages and isolated apps.',
  },
];

export const MOCK_MEMORIES: HermesMemory[] = [
  {
    id: 'mem-001',
    title: 'MEMORY.md',
    path: 'memories/MEMORY.md',
    updatedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    originDevice: 'dev-desktop-001',
    originDeviceName: 'Studio PC',
    revision: 142,
    isLatest: true,
    devicesWithRevision: ['dev-desktop-001', 'dev-zenbook-002'],
    content: `# Core User Preferences & Context

- Preferred OS: Windows 11 with PowerShell & WSL2
- Primary Editor: VS Code / Cursor
- Coding Style: Strict TypeScript, modular adapters, defensive error handling
- Networking: private Tailscale mesh 100.64.10.0/24
- P2P Engine: Syncthing v1.27+
`,
  },
  {
    id: 'mem-002',
    title: 'Project Architecture Conventions',
    path: 'memories/architecture_notes.md',
    updatedAt: new Date(Date.now() - 3 * 3600 * 1000).toISOString(),
    originDevice: 'dev-zenbook-002',
    originDeviceName: 'Travel Laptop',
    revision: 78,
    isLatest: true,
    devicesWithRevision: ['dev-desktop-001', 'dev-zenbook-002'],
    content: `# Architecture Guidelines
- Always decouple transport (Syncthing) from live agent files
- Use SQLite VACUUM or atomic snapshots before exporting
- All secrets must be encrypted at rest with AES-256-GCM
`,
  },
  {
    id: 'mem-003',
    title: 'Lab Network Configuration',
    path: 'memories/network_topology.md',
    updatedAt: new Date(Date.now() - 28 * 3600 * 1000).toISOString(),
    originDevice: 'dev-desktop-001',
    originDeviceName: 'Studio PC',
    revision: 29,
    isLatest: true,
    devicesWithRevision: ['dev-desktop-001', 'dev-zenbook-002'],
    content: `# Tailscale Subnets
- Studio PC: 100.64.10.11
- Travel Laptop: 100.64.10.12
- Lab Laptop: 100.64.10.13
`,
  },
];

export const MOCK_SKILLS: HermesSkill[] = [
  {
    id: 'skill-001',
    name: 'Cybersecurity',
    description: 'Vulnerability assessment, network analysis, and exploit mitigation scripts.',
    filesCount: 8,
    lastModified: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    originDevice: 'dev-desktop-001',
    originDeviceName: 'Studio PC',
    revision: 34,
    devicesWithRevision: ['dev-desktop-001', 'dev-zenbook-002'],
    tags: ['Security', 'Offensive', 'Hardening'],
  },
  {
    id: 'skill-002',
    name: 'Development',
    description: 'TypeScript, React, Electron, and Rust scaffolding and debugging tools.',
    filesCount: 14,
    lastModified: new Date(Date.now() - 4 * 3600 * 1000).toISOString(),
    originDevice: 'dev-zenbook-002',
    originDeviceName: 'Travel Laptop',
    revision: 51,
    devicesWithRevision: ['dev-desktop-001', 'dev-zenbook-002'],
    tags: ['Coding', 'Refactoring', 'Testing'],
  },
  {
    id: 'skill-003',
    name: 'University & Research',
    description: 'Academic paper summarization, KaTeX math parsing, and bibliographic notes.',
    filesCount: 5,
    lastModified: new Date(Date.now() - 24 * 3600 * 1000).toISOString(),
    originDevice: 'dev-desktop-001',
    originDeviceName: 'Studio PC',
    revision: 12,
    devicesWithRevision: ['dev-desktop-001', 'dev-zenbook-002'],
    tags: ['Research', 'LaTeX', 'Study'],
  },
  {
    id: 'skill-004',
    name: 'System Administration',
    description: 'Automated PowerShell diagnostics, cron setups, and daemon management.',
    filesCount: 6,
    lastModified: new Date(Date.now() - 48 * 3600 * 1000).toISOString(),
    originDevice: 'dev-laptop-003',
    originDeviceName: 'Lab Laptop',
    revision: 9,
    devicesWithRevision: ['dev-desktop-001', 'dev-zenbook-002', 'dev-laptop-003'],
    tags: ['DevOps', 'Windows', 'Linux'],
  },
];

export const MOCK_FILES: HermesFile[] = [
  {
    id: 'f-001',
    name: 'config.yaml',
    category: 'Configuration',
    path: 'C:\\Users\\demo\\AppData\\Local\\hermes\\config.yaml',
    size: 4336,
    modifiedAt: new Date(Date.now() - 1 * 3600 * 1000).toISOString(),
    sha256: 'e3b0c44298fc1c149afbf4c8996fb92427ae41e4649b934ca495991b7852b855',
    originDevice: 'dev-desktop-001',
    originDeviceName: 'Studio PC',
    revision: 28,
    syncStatus: 'synced',
  },
  {
    id: 'f-002',
    name: 'SOUL.md',
    category: 'Configuration',
    path: 'C:\\Users\\demo\\AppData\\Local\\hermes\\SOUL.md',
    size: 667,
    modifiedAt: new Date(Date.now() - 10 * 3600 * 1000).toISOString(),
    sha256: '9f86d081884c7d659a2feaa0c55ad015a3bf4f1b2b0b822cd15d6c15b0f00a08',
    originDevice: 'dev-desktop-001',
    originDeviceName: 'Studio PC',
    revision: 19,
    syncStatus: 'synced',
  },
  {
    id: 'f-003',
    name: 'MEMORY.md',
    category: 'Memories',
    path: 'C:\\Users\\demo\\AppData\\Local\\hermes\\memories\\MEMORY.md',
    size: 82400,
    modifiedAt: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    sha256: '5e884898da28047151d0e56f8dc6292773603d0d6aabbdd62a11ef721d1542d8',
    originDevice: 'dev-desktop-001',
    originDeviceName: 'Studio PC',
    revision: 142,
    syncStatus: 'synced',
  },
  {
    id: 'f-004',
    name: 'cybersecurity-toolkit.ts',
    category: 'Skills',
    path: 'C:\\Users\\demo\\AppData\\Local\\hermes\\skills\\research\\toolkit.ts',
    size: 14890,
    modifiedAt: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    sha256: '4b227777d4dd1fc61c6f884f48641d02b4d121d3fd328cb08b5531fcacdabf8a',
    originDevice: 'dev-desktop-001',
    originDeviceName: 'Studio PC',
    revision: 34,
    syncStatus: 'synced',
  },
  {
    id: 'f-005',
    name: 'session_export_2026-09-25.jsonl',
    category: 'Sessions/Exports',
    path: 'C:\\Users\\demo\\AppData\\Local\\hermes\\sessions\\export.jsonl',
    size: 1245000,
    modifiedAt: new Date(Date.now() - 5 * 3600 * 1000).toISOString(),
    sha256: 'ef2d127de37b942baad06145e54b0c619a1f22327b2ebbcfbec78f5564afe39d',
    originDevice: 'dev-zenbook-002',
    originDeviceName: 'Travel Laptop',
    revision: 8,
    syncStatus: 'synced',
  },
  {
    id: 'f-006',
    name: 'hermes-agent.log',
    category: 'Logs',
    path: 'C:\\Users\\demo\\AppData\\Local\\hermes\\runtime\\hermes.log',
    size: 89400,
    modifiedAt: new Date(Date.now() - 10 * 60 * 1000).toISOString(),
    sha256: '8c6976e5b5410415bde908bd4dee15dfb167a9c873fc4bb8a81f6f2ab448a918',
    originDevice: 'dev-desktop-001',
    originDeviceName: 'Studio PC',
    revision: 67,
    syncStatus: 'synced',
  },
];

export const MOCK_VAULT_SECRETS: VaultSecret[] = [
  {
    id: 'sec-001',
    key: 'OPENROUTER_API_KEY',
    category: 'API Keys',
    value: 'sk-or-v1-98a417df8b6e2104bcde190847321fa890123ef',
    description: 'Primary model router key for Claude 3.5 & DeepSeek R1',
    isMasked: true,
    updatedAt: new Date(Date.now() - 4 * 24 * 3600 * 1000).toISOString(),
    originDevice: 'Studio PC',
  },
  {
    id: 'sec-002',
    key: 'OPENAI_API_KEY',
    category: 'API Keys',
    value: 'sk-proj-a8f9024bcde99102456711892305718293',
    description: 'GPT-4o fallback and embedding token',
    isMasked: true,
    updatedAt: new Date(Date.now() - 10 * 24 * 3600 * 1000).toISOString(),
    originDevice: 'Studio PC',
  },
  {
    id: 'sec-003',
    key: 'ANTHROPIC_API_KEY',
    category: 'API Keys',
    value: 'sk-ant-api03-99b8214faec019283471018273645',
    description: 'Direct Anthropic API key',
    isMasked: true,
    updatedAt: new Date(Date.now() - 12 * 24 * 3600 * 1000).toISOString(),
    originDevice: 'Travel Laptop',
  },
  {
    id: 'sec-004',
    key: 'TAILSCALE_AUTHKEY',
    category: 'Tailscale',
    value: 'tskey-auth-k92840192847102948-nodekey',
    description: 'Pre-authenticated key for automated node joining',
    isMasked: true,
    updatedAt: new Date(Date.now() - 18 * 24 * 3600 * 1000).toISOString(),
    originDevice: 'Studio PC',
  },
];

export const MOCK_ACTIVITY: ActivityEvent[] = [
  {
    id: 'act-001',
    timestamp: new Date(Date.now() - 42 * 1000).toISOString(),
    type: 'file_sync',
    title: 'MEMORY.md updated',
    description: 'Studio PC → Travel Laptop (revision 142)',
    sourceDevice: 'Studio PC',
    targetDevice: 'Travel Laptop',
    bytesTransferred: 82400,
    filesCount: 1,
    status: 'success',
  },
  {
    id: 'act-002',
    timestamp: new Date(Date.now() - 95 * 1000).toISOString(),
    type: 'session_imported',
    title: 'Session imported',
    description: 'Security lab review (97 messages) indexed locally',
    sourceDevice: 'Studio PC',
    targetDevice: 'Travel Laptop',
    filesCount: 1,
    status: 'success',
  },
  {
    id: 'act-003',
    timestamp: new Date(Date.now() - 15 * 60 * 1000).toISOString(),
    type: 'file_sync',
    title: '42 files synchronized',
    description: 'Incremental sync cycle completed (128.4 MB)',
    sourceDevice: 'Studio PC',
    targetDevice: 'Travel Laptop',
    bytesTransferred: 128.4 * 1024 * 1024,
    filesCount: 42,
    status: 'success',
  },
  {
    id: 'act-004',
    timestamp: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    type: 'device_connect',
    title: 'Device connected',
    description: 'Travel Laptop established a direct P2P mesh connection over Tailscale',
    sourceDevice: 'Travel Laptop',
    status: 'info',
  },
  {
    id: 'act-005',
    timestamp: new Date(Date.now() - 2 * 3600 * 1000).toISOString(),
    type: 'backup_created',
    title: 'Automated snapshot backup created',
    description: 'Safe snapshot archive generated (248 MB)',
    sourceDevice: 'Studio PC',
    bytesTransferred: 248 * 1024 * 1024,
    status: 'success',
  },
];

export const MOCK_BACKUPS: BackupRecord[] = [
  {
    id: 'bak-001',
    name: 'hub-backup-2026-09-26-01-45.tar.gz',
    createdAt: new Date(Date.now() - 45 * 60 * 1000).toISOString(),
    sizeBytes: 248 * 1024 * 1024,
    health: 'valid',
    itemCounts: {
      sessions: 243,
      memories: 52,
      skills: 18,
      configs: 6,
    },
    originDevice: 'Studio PC',
  },
  {
    id: 'bak-002',
    name: 'hub-backup-2026-09-25-02-00.tar.gz',
    createdAt: new Date(Date.now() - 25 * 3600 * 1000).toISOString(),
    sizeBytes: 236 * 1024 * 1024,
    health: 'valid',
    itemCounts: {
      sessions: 239,
      memories: 50,
      skills: 18,
      configs: 6,
    },
    originDevice: 'Studio PC',
  },
];
